ALTER TABLE "SeasonEvent" ADD COLUMN IF NOT EXISTS "allDay" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "SeasonEvent" ADD COLUMN IF NOT EXISTS "startTime" TEXT;
ALTER TABLE "SeasonEvent" ADD COLUMN IF NOT EXISTS "endTime" TEXT;
ALTER TABLE "SeasonEvent" ADD COLUMN IF NOT EXISTS "location" TEXT;
